Remove conversationId as foreignKey on Message DB model
This is inconsistently causing an exception being thrown in MessagesService (line 296)
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
```

MAILAND-1442