Bump Core Auth and Core Presentation
Auth [1.17.5] -> [1.18]
Presentation [1.18.1] -> [1.18.3]

This fixes a crash during login due to NoSuchMethodError

MAILAND-2557